# SPDX-License-Identifier: GPL-2.0-only
KBUILD_CFLAGS += -ffunction-sections
obj-$(CONFIG_SAMPLE_TEST_MODULE) += test_module.o
# CFLAGS_f_fs.o += -fpass-plugin=/root/llvm-tutor/build/lib/libBoundaryCounter.so
